version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cognito-user-pool"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2zk3jncixruc"
s3_prefix = "cognito-user-pool"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
